routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/create-profile','HomeController@createProfile')->name('create.profile');
Route::patch('/update-profile','HomeController@updateProfile')->name('update.profile');

Route::middleware(['is_admin'])->name('admin.')->prefix('admin')->group(function(){
	Route::get('home', 'HomeController@adminHome')->name('home');
	Route::resource('user-profile', 'ProfileController');
});

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $table    = 'profiles';
    protected $fillable = ['user_id','nama_lengkap','nik','jenis_kelamin','tempat','tanggal','alamat','agama','foto_profil'];
    
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profil()
    {
        return $this->hasOne(Profile::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profile;

class HomeController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}
	public function index()
	{
		$profile = Profile::where('user_id',auth()->user()->id)->first();
		return view('home', compact('profile'));
	}
	public function adminHome()
	{
		return view('admin.home');
	}
	public function createProfile(Request $request){
		$request->validate([
			'nama_lengkap'  => 'required',
			'nik'           => 'required',
			'jenis_kelamin' => 'required',
			'tempat'        => 'required',
			'tanggal'       => 'required',
			'alamat'        => 'required',
			'agama'         => 'required',
			'foto_profil'   => 'mimes:jpeg,png,jpg,gif,svg|max:2048'
		]);

		$profil = Profile::create($request->all());
		if (is_null($request->foto_profil)) {
			$imageName = 'img/default.png';
		} else {
			$nameimg 	= time().'.'.$request->foto_profil->extension();  
			$request->foto_profil->move(public_path('img'), $nameimg);
			$imageName 	= 'img/'.$nameimg;
		}
		$profil->foto_profil 	= $imageName;
		$profil->user_id 		= auth()->user()->id;
		$profil->save();

		
		return redirect()->back();
	}
	public function updateProfile(Request $request){
		$profil 				= Profile::where('user_id',auth()->user()->id)->first();
		$profil->nama_lengkap 	= $request->nama_lengkap;
		$profil->nik 			= $request->nik;
		$profil->jenis_kelamin 	= $request->jenis_kelamin;
		$profil->tempat 		= $request->tempat;
		$profil->tanggal 		= $request->tanggal;
		$profil->alamat 		= $request->alamat;
		$profil->agama 			= $request->agama;

		if (is_null($request->foto_profil)) {
			$imageName 	= $profil->foto_profil;
		} else {
			$nameimg 	= time().'.'.$request->foto_profil->extension();  
			$request->foto_profil->move(public_path('img'), $nameimg);
			$imageName 	= 'img/'.$nameimg;
		}

		$profil->foto_profil 	= $imageName;
		// dd($profil);
		$profil->save();
		return redirect()->back();
	}
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Profile;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
	public function __construct()
	{
		$this->middleware('auth');
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$profile = Profile::with('user')->orderBy('id','asc')->get();
		return view('admin.profile.index', compact('profile'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		// dd($request->all());
		$request->validate([
			'nama_lengkap'  => 'required',
			'nik'           => 'required',
			'jenis_kelamin' => 'required',
			'tempat'        => 'required',
			'tanggal'       => 'required',
			'alamat'        => 'required',
			'agama'         => 'required',
			'foto_profil'   => 'mimes:jpeg,png,jpg,gif,svg|max:2048',
			'email'         => ['required', 'string', 'email', 'max:255', 'unique:users'],
			'password'      => ['required', 'string', 'min:8'],
		]);
		
		$user = new User;
		$user->name     = $request->nama_lengkap;
		$user->email    = $request->email;
		$user->password = Hash::make($request->password);
		$user->save();

		$profil = Profile::create($request->all());
		if (is_null($request->foto_profil)) {
			$imageName 	= 'img/default.png';
		} else {
			$nameimg 	= time().'.'.$request->foto_profil->extension();  
			$request->foto_profil->move(public_path('img'), $nameimg);
			$imageName 	= 'img/'.$nameimg;
		}
		$profil->foto_profil 	= $imageName;
		$profil->user_id 		= $user->id;
		$profil->save();

		
		return redirect()->back();
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  \App\Profile  $profile
	 * @return \Illuminate\Http\Response
	 */
	public function show(Profile $profile)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  \App\Profile  $profile
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Profile $profile)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \App\Profile  $profile
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, Profile $profile)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  \App\Profile  $profile
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		$profil = Profile::find($id);
		$userid = User::where('id',$profil->user_id)->first();
		$userid->delete();
		$profil->delete();
		return redirect()->back();
	}
}

resources/views/admin/home.blade.php
@extends('layouts.app')
   
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    You are Admin.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/profile/form.blade.php
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<label for="">Nama Lengkap</label>
			<input type="text" class="form-control" id="nama_lengkap" name="nama_lengkap" placeholder="Nama Lengkap">
		</div>
		<div class="form-group">
			<label for="">Email</label>
			<input type="text" class="form-control" id="email" name="email" placeholder="Email Anda">
		</div>
		<div class="form-group">
			<label for="">Password</label>
			<input type="password" class="form-control" id="password" name="password" placeholder="Password Anda">
		</div>
		<div class="form-group">
			<label for="">Alamat</label>
			<textarea name="alamat" id="alamat" rows="3" class="form-control" placeholder="Alamat Anda"></textarea>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label for="">NIK</label>
			<input type="number" class="form-control" id="nik" name="nik" placeholder="NIK">
		</div>
		<div class="form-group">
			<label for="">Jenis Kelamin</label>
			<select name="jenis_kelamin" id="jenis_kelamin" class="form-control">
				<option>Pilih Jenis Kelamin</option>
				<option value="laki-laki">Laki-Laki</option>
				<option value="perempuan">Perempuan</option>
			</select>
		</div>
		<div class="form-group">
			<div class="row">
				<div class="col">
					<label for="">Tempat Lahir</label>
					<input type="text" class="form-control" name="tempat" id="tempat" placeholder="Tempat Lahir">
				</div>
				<div class="col">
					<label for="">Tanggal Lahir</label>
					<input type="text" class="form-control" name="tanggal" id="tanggal" placeholder="Tanggal Lahir">
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="">Agama</label>
			<select name="agama" id="agama" class="form-control">
				<option>Pilih Agama</option>
				<option value="islam">Islam</option>
				<option value="hindu">Hindu</option>
				<option value="buddha">Buddha</option>
				<option value="kristen">Kristen</option>
			</select>
		</div>
		<div class="form-group">
			<label for="">Foto Profil</label>
			<input type="file" name="foto_profil" class="form-control" accept="image/png, image/jpg, image/jpeg">
		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group text-center">
			<button type="submit" class="btn btn-primary">Submit Data</button>
		</div>
	</div>
</div>

resources/views/admin/profile/form_edit.blade.php
<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<label for="">Nama Lengkap</label>
			<input type="text" class="form-control" id="nama_lengkap" name="nama_lengkap" placeholder="Nama Lengkap" value="{{ $profile->nama_lengkap }}">
		</div>
		<div class="form-group">
			<label for="">Alamat</label>
			<textarea name="alamat" id="alamat" rows="3" class="form-control" placeholder="Alamat Anda">{{ $profile->alamat }}</textarea>
		</div>
		<div class="form-group">
			<label for="">NIK</label>
			<input type="number" class="form-control" id="nik" name="nik" placeholder="NIK" value="{{ $profile->nik }}">
		</div>
		<div class="form-group">
			<label for="">Jenis Kelamin</label>
			<select name="jenis_kelamin" id="jenis_kelamin" class="form-control">
				<option>Pilih Jenis Kelamin</option>
				<option value="laki-laki" {{ $profile->jenis_kelamin == 'laki-laki' ? 'selected' : '' }}>Laki-Laki</option>
				<option value="perempuan" {{ $profile->jenis_kelamin == 'perempuan' ? 'selected' : '' }}>Perempuan</option>
			</select>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<div class="row">
				<div class="col">
					<label for="">Tempat Lahir</label>
					<input type="text" class="form-control" name="tempat" id="tempat" placeholder="Tempat Lahir" value="{{ $profile->tempat }}">
				</div>
				<div class="col">
					<label for="">Tanggal Lahir</label>
					<input type="text" class="form-control" name="tanggal" id="tanggal" placeholder="Tanggal Lahir" value="{{ $profile->tanggal }}">
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="">Agama</label>
			<select name="agama" id="agama" class="form-control">
				<option>Pilih Agama</option>
				<option value="islam" {{ $profile->agama == 'islam' ? 'selected' : '' }}>Islam</option>
				<option value="hindu" {{ $profile->agama == 'hindu' ? 'selected' : '' }}>Hindu</option>
				<option value="buddha" {{ $profile->agama == 'buddha' ? 'selected' : '' }}>Buddha</option>
				<option value="kristen" {{ $profile->agama == 'kristen' ? 'selected' : '' }}>Kristen</option>
			</select>
		</div>
		<div class="form-group">
			<label for="">Foto Profil</label>
			<input type="file" name="foto_profil" class="form-control" accept="image/png, image/jpg, image/jpeg">
			<img src="{{ asset($profile->foto_profil) }}" class="img-fluid" width="30%">
		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group text-center">
			<button type="submit" class="btn btn-primary">Edit Data</button>
		</div>
	</div>
</div>

resources/views/admin/profile/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-12 mb-3">
			<div class="card">
				<div class="card-header">
					<span class="badge badge-success">Add User Profile</span>
				</div>
				<div class="card-body">
					<div class="col-md-12">
						<form action="{{ route('admin.user-profile.store') }}" enctype="multipart/form-data" method="POST">
							@csrf
							@include('admin.profile.form')
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<span class="badge badge-primary">View User Profile</span>
				</div>
				<div class="card-body">
					@include('admin.profile.table')
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@push('style')
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/dataTables.bootstrap4.min.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme/dist/select2-bootstrap4.min.css">
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
@endpush
@push('script')
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script>
	$(document).ready(function() {
	    $('#example').DataTable();
	    $('select').select2({
		    theme: 'bootstrap4',
		});
		$('#tanggal').datepicker({
            uiLibrary: 'bootstrap4'
        });
	} );
</script>
@endpush

resources/views/admin/profile/table.blade.php
<table id="example" class="table table-striped table-bordered" style="width:100%">
	<thead>
		<tr>
			<th>No.</th>
			<th>Email Login</th>
			<th>Nama Lengkap</th>
			<th>Jenis Kelamin</th>
			<th>TTL</th>
			<th>Agama</th>
			<th>Foto Profil</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach($profile as $p)
		<tr>
			<td>{{ $loop->iteration }}</td>
			<td>{{ $p->user->email }}</td>
			<td>{{ ucwords($p->nama_lengkap) }}</td>
			<td>{{ ucwords($p->jenis_kelamin) }}</td>
			<td>{{ ucwords($p->tempat) }}, {{ $p->tanggal }}</td>
			<td>{{ ucwords($p->agama) }}</td>
			<td><img src="{{ asset($p->foto_profil) }}" class="rounded-circle" alt="{{ ucwords($p->nama_lengkap) }}" style="width: 30%;"></td>
			<td>
				<form action="{{ route('admin.user-profile.destroy',$p->id) }}" method="POST">
					@csrf
					@method('DELETE')
					<button type="submit" class="btn btn-danger" onclick="return confirm('yakin mau hapus data ini?');">Delete</button>
				</form>
			</td>
		</tr>
		@endforeach
	</tbody>
	<tfoot>
		<tr>
			<th>No.</th>
			<th>Email Login</th>
			<th>Nama Lengkap</th>
			<th>Jenis Kelamin</th>
			<th>TTL</th>
			<th>Agama</th>
			<th>Foto Profil</th>
			<th></th>
		</tr>
	</tfoot>
</table>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">Edit User Profile</div>
				<div class="card-body">
					@if(is_null($profile))
					<form action="{{ route('create.profile') }}" enctype="multipart/form-data" method="POST">
						@csrf
						@include('admin.profile.form')
					</form>
					@else
					<form action="{{ route('update.profile') }}" enctype="multipart/form-data" method="POST">
						@csrf
						@method('PATCH')
						@include('admin.profile.form_edit')
					</form>
					@endif
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @stack('style')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            @if(auth()->check() && auth()->user()->is_admin == '1')
                            <a href="{{ route('admin.user-profile.index') }}" class="nav-link">User Management</a>
                            @else
                            @endif
                        </li>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a href="#" class="dropdown-item">Profil</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="{{ asset('js/app.js') }}" defer></script>
    @stack('script')
</body>
</html>